name: Upload Website To S3

on:
  push:
    branches:
      - main

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: GitHub Action for npx
        uses: mikeal/npx@1.0.0

      - run: npm install
      - run: npm run lint
      - run: npm run check
      - run: npm run build

  deploy:
    name: deploy
    needs: check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - run: npm install

      - name: Deploy static site to S3 bucket
        run: npm run deploy
